# {
#   title: "InterFlex Vlab"
#   configuration_version: "0.2"
#   last_updated: "11.01.2019"
# }

version: '3'

services:
  vlab-mqtt-broker:
    image: eclipse-mosquitto
    environment:
      - OWNER=AIT
    container_name: iflex-vlab-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    network_mode: "host"
    
  vlab-config:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    ports:
      - "10101:10101"
    command: config
    container_name: iflex-vlab-config
    network_mode: "host"
    
  vlab-admin:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
      - LLSIMDESC_NAME="InterFlex VLab Microgrid Example"
      - LLSIMDESC_INFO="A simple exaple of a Microgrid model running with AIT Lablink."
      - LLSIMDESC_URL="https://github.com/forinterflex/vlab-setup"
    command: admin
    depends_on:
      - vlab-config
      - vlab-mqtt-broker
    ports:
      - "8080:8080"
    container_name: iflex-vlab-admin
    network_mode: "host"
    
  vlab-load1:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    command: load1
    container_name: iflex-vlab-load1
    depends_on:
      - vlab-config
      - vlab-mqtt-broker
    stdin_open: true
    tty: true
    network_mode: "host"
    
  vlab-load2:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    command: load2
    container_name: iflex-vlab-load2
    depends_on:
      - vlab-config
      - vlab-mqtt-broker
    stdin_open: true
    tty: true
    network_mode: "host"
      
  vlab-load3:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    command: load3
    container_name: iflex-vlab-load3
    depends_on:
      - vlab-config
      - vlab-mqtt-broker
    stdin_open: true
    tty: true
    network_mode: "host"
      
  vlab-battery:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    command: battery       
    container_name: iflex-vlab-battery
    depends_on:
      - vlab-config
      - vlab-mqtt-broker    
    stdin_open: true
    tty: true
    network_mode: "host"

  vlab-pvgen:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    command: pvgen       
    container_name: iflex-vlab-pvgen
    depends_on:
      - vlab-config
      - vlab-mqtt-broker    
    stdin_open: true
    tty: true
    network_mode: "host"
    
  vlab-breaker:
    image: forinterflex/vlab:ait-v0.1
    environment:
      - OWNER=AIT
    command: breaker 
    container_name: iflex-vlab-breaker
    depends_on:
      - vlab-config
      - vlab-mqtt-broker    
    stdin_open: true
    tty: true
    network_mode: "host"

